# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

apiKey: Optional[str]
"""
Your API Key from the https://my.hivelocity.net portal.
"""

apiUrl: Optional[str]
"""
The API instance to communicate with defaults to https://core.hivelocity.net/api/v2
"""

