# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('hivelocity')


class _ExportableConfig(types.ModuleType):
    @property
    def api_key(self) -> Optional[str]:
        """
        Your API Key from the https://my.hivelocity.net portal.
        """
        return __config__.get('apiKey')

    @property
    def api_url(self) -> Optional[str]:
        """
        The API instance to communicate with defaults to https://core.hivelocity.net/api/v2
        """
        return __config__.get('apiUrl')

