// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Hivelocity
{
    public static class GetDevicePort
    {
        public static Task<GetDevicePortResult> InvokeAsync(GetDevicePortArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDevicePortResult>("hivelocity:index/getDevicePort:getDevicePort", args ?? new GetDevicePortArgs(), options.WithDefaults());

        public static Output<GetDevicePortResult> Invoke(GetDevicePortInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDevicePortResult>("hivelocity:index/getDevicePort:getDevicePort", args ?? new GetDevicePortInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDevicePortArgs : global::Pulumi.InvokeArgs
    {
        [Input("deviceId", required: true)]
        public int DeviceId { get; set; }

        [Input("filters")]
        private List<Inputs.GetDevicePortFilterArgs>? _filters;
        public List<Inputs.GetDevicePortFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetDevicePortFilterArgs>());
            set => _filters = value;
        }

        [Input("first")]
        public bool? First { get; set; }

        public GetDevicePortArgs()
        {
        }
        public static new GetDevicePortArgs Empty => new GetDevicePortArgs();
    }

    public sealed class GetDevicePortInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("deviceId", required: true)]
        public Input<int> DeviceId { get; set; } = null!;

        [Input("filters")]
        private InputList<Inputs.GetDevicePortFilterInputArgs>? _filters;
        public InputList<Inputs.GetDevicePortFilterInputArgs> Filters
        {
            get => _filters ?? (_filters = new InputList<Inputs.GetDevicePortFilterInputArgs>());
            set => _filters = value;
        }

        [Input("first")]
        public Input<bool>? First { get; set; }

        public GetDevicePortInvokeArgs()
        {
        }
        public static new GetDevicePortInvokeArgs Empty => new GetDevicePortInvokeArgs();
    }


    [OutputType]
    public sealed class GetDevicePortResult
    {
        public readonly int DeviceId;
        public readonly ImmutableArray<Outputs.GetDevicePortFilterResult> Filters;
        public readonly bool? First;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool IsBond;
        public readonly string Name;
        public readonly int PortId;
        public readonly bool Private;

        [OutputConstructor]
        private GetDevicePortResult(
            int deviceId,

            ImmutableArray<Outputs.GetDevicePortFilterResult> filters,

            bool? first,

            string id,

            bool isBond,

            string name,

            int portId,

            bool @private)
        {
            DeviceId = deviceId;
            Filters = filters;
            First = first;
            Id = id;
            IsBond = isBond;
            Name = name;
            PortId = portId;
            Private = @private;
        }
    }
}
