// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Hivelocity
{
    [Obsolete(@"hivelocity.index/gethivelocitydeviceport.getHivelocityDevicePort has been deprecated in favor of hivelocity.index/getdeviceport.getDevicePort")]
    public static class GetHivelocityDevicePort
    {
        public static Task<GetHivelocityDevicePortResult> InvokeAsync(GetHivelocityDevicePortArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetHivelocityDevicePortResult>("hivelocity:index/getHivelocityDevicePort:getHivelocityDevicePort", args ?? new GetHivelocityDevicePortArgs(), options.WithDefaults());

        public static Output<GetHivelocityDevicePortResult> Invoke(GetHivelocityDevicePortInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetHivelocityDevicePortResult>("hivelocity:index/getHivelocityDevicePort:getHivelocityDevicePort", args ?? new GetHivelocityDevicePortInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetHivelocityDevicePortArgs : global::Pulumi.InvokeArgs
    {
        [Input("deviceId", required: true)]
        public int DeviceId { get; set; }

        [Input("filters")]
        private List<Inputs.GetHivelocityDevicePortFilterArgs>? _filters;
        public List<Inputs.GetHivelocityDevicePortFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetHivelocityDevicePortFilterArgs>());
            set => _filters = value;
        }

        [Input("first")]
        public bool? First { get; set; }

        public GetHivelocityDevicePortArgs()
        {
        }
        public static new GetHivelocityDevicePortArgs Empty => new GetHivelocityDevicePortArgs();
    }

    public sealed class GetHivelocityDevicePortInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("deviceId", required: true)]
        public Input<int> DeviceId { get; set; } = null!;

        [Input("filters")]
        private InputList<Inputs.GetHivelocityDevicePortFilterInputArgs>? _filters;
        public InputList<Inputs.GetHivelocityDevicePortFilterInputArgs> Filters
        {
            get => _filters ?? (_filters = new InputList<Inputs.GetHivelocityDevicePortFilterInputArgs>());
            set => _filters = value;
        }

        [Input("first")]
        public Input<bool>? First { get; set; }

        public GetHivelocityDevicePortInvokeArgs()
        {
        }
        public static new GetHivelocityDevicePortInvokeArgs Empty => new GetHivelocityDevicePortInvokeArgs();
    }


    [OutputType]
    public sealed class GetHivelocityDevicePortResult
    {
        public readonly int DeviceId;
        public readonly ImmutableArray<Outputs.GetHivelocityDevicePortFilterResult> Filters;
        public readonly bool? First;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool IsBond;
        public readonly string Name;
        public readonly int PortId;
        public readonly bool Private;

        [OutputConstructor]
        private GetHivelocityDevicePortResult(
            int deviceId,

            ImmutableArray<Outputs.GetHivelocityDevicePortFilterResult> filters,

            bool? first,

            string id,

            bool isBond,

            string name,

            int portId,

            bool @private)
        {
            DeviceId = deviceId;
            Filters = filters;
            First = first;
            Id = id;
            IsBond = isBond;
            Name = name;
            PortId = portId;
            Private = @private;
        }
    }
}
