// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Hivelocity
{
    [HivelocityResourceType("hivelocity:index/orderGroupDetail:OrderGroupDetail")]
    public partial class OrderGroupDetail : global::Pulumi.CustomResource
    {
        /// <summary>
        /// A list of Bare Metal Devices to deploy
        /// </summary>
        [Output("bareMetalDevices")]
        public Output<ImmutableArray<Outputs.OrderGroupDetailBareMetalDevice>> BareMetalDevices { get; private set; } = null!;

        /// <summary>
        /// Name of this Order Group
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Devices will be placed in the same rack
        /// </summary>
        [Output("sameRack")]
        public Output<bool> SameRack { get; private set; } = null!;


        /// <summary>
        /// Create a OrderGroupDetail resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public OrderGroupDetail(string name, OrderGroupDetailArgs args, CustomResourceOptions? options = null)
            : base("hivelocity:index/orderGroupDetail:OrderGroupDetail", name, args ?? new OrderGroupDetailArgs(), MakeResourceOptions(options, ""))
        {
        }

        private OrderGroupDetail(string name, Input<string> id, OrderGroupDetailState? state = null, CustomResourceOptions? options = null)
            : base("hivelocity:index/orderGroupDetail:OrderGroupDetail", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                Aliases =
                {
                    new global::Pulumi.Alias { Type = "hivelocity:index/orderGroup:orderGroup" },
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing OrderGroupDetail resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static OrderGroupDetail Get(string name, Input<string> id, OrderGroupDetailState? state = null, CustomResourceOptions? options = null)
        {
            return new OrderGroupDetail(name, id, state, options);
        }
    }

    public sealed class OrderGroupDetailArgs : global::Pulumi.ResourceArgs
    {
        [Input("bareMetalDevices", required: true)]
        private InputList<Inputs.OrderGroupDetailBareMetalDeviceArgs>? _bareMetalDevices;

        /// <summary>
        /// A list of Bare Metal Devices to deploy
        /// </summary>
        public InputList<Inputs.OrderGroupDetailBareMetalDeviceArgs> BareMetalDevices
        {
            get => _bareMetalDevices ?? (_bareMetalDevices = new InputList<Inputs.OrderGroupDetailBareMetalDeviceArgs>());
            set => _bareMetalDevices = value;
        }

        /// <summary>
        /// Name of this Order Group
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Devices will be placed in the same rack
        /// </summary>
        [Input("sameRack", required: true)]
        public Input<bool> SameRack { get; set; } = null!;

        public OrderGroupDetailArgs()
        {
        }
        public static new OrderGroupDetailArgs Empty => new OrderGroupDetailArgs();
    }

    public sealed class OrderGroupDetailState : global::Pulumi.ResourceArgs
    {
        [Input("bareMetalDevices")]
        private InputList<Inputs.OrderGroupDetailBareMetalDeviceGetArgs>? _bareMetalDevices;

        /// <summary>
        /// A list of Bare Metal Devices to deploy
        /// </summary>
        public InputList<Inputs.OrderGroupDetailBareMetalDeviceGetArgs> BareMetalDevices
        {
            get => _bareMetalDevices ?? (_bareMetalDevices = new InputList<Inputs.OrderGroupDetailBareMetalDeviceGetArgs>());
            set => _bareMetalDevices = value;
        }

        /// <summary>
        /// Name of this Order Group
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Devices will be placed in the same rack
        /// </summary>
        [Input("sameRack")]
        public Input<bool>? SameRack { get; set; }

        public OrderGroupDetailState()
        {
        }
        public static new OrderGroupDetailState Empty => new OrderGroupDetailState();
    }
}
