// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Hivelocity
{
    [Obsolete(@"hivelocity.index/ordergroup.orderGroup has been deprecated in favor of hivelocity.index/ordergroupdetail.OrderGroupDetail")]
    [HivelocityResourceType("hivelocity:index/orderGroup:orderGroup")]
    public partial class OrderGroup : global::Pulumi.CustomResource
    {
        /// <summary>
        /// A list of Bare Metal Devices to deploy
        /// </summary>
        [Output("bareMetalDevices")]
        public Output<ImmutableArray<Outputs.OrderGroupBareMetalDevice>> BareMetalDevices { get; private set; } = null!;

        /// <summary>
        /// Name of this Order Group
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Devices will be placed in the same rack
        /// </summary>
        [Output("sameRack")]
        public Output<bool> SameRack { get; private set; } = null!;


        /// <summary>
        /// Create a OrderGroup resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public OrderGroup(string name, OrderGroupArgs args, CustomResourceOptions? options = null)
            : base("hivelocity:index/orderGroup:orderGroup", name, args ?? new OrderGroupArgs(), MakeResourceOptions(options, ""))
        {
        }

        private OrderGroup(string name, Input<string> id, OrderGroupState? state = null, CustomResourceOptions? options = null)
            : base("hivelocity:index/orderGroup:orderGroup", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing OrderGroup resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static OrderGroup Get(string name, Input<string> id, OrderGroupState? state = null, CustomResourceOptions? options = null)
        {
            return new OrderGroup(name, id, state, options);
        }
    }

    public sealed class OrderGroupArgs : global::Pulumi.ResourceArgs
    {
        [Input("bareMetalDevices", required: true)]
        private InputList<Inputs.OrderGroupBareMetalDeviceArgs>? _bareMetalDevices;

        /// <summary>
        /// A list of Bare Metal Devices to deploy
        /// </summary>
        public InputList<Inputs.OrderGroupBareMetalDeviceArgs> BareMetalDevices
        {
            get => _bareMetalDevices ?? (_bareMetalDevices = new InputList<Inputs.OrderGroupBareMetalDeviceArgs>());
            set => _bareMetalDevices = value;
        }

        /// <summary>
        /// Name of this Order Group
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Devices will be placed in the same rack
        /// </summary>
        [Input("sameRack", required: true)]
        public Input<bool> SameRack { get; set; } = null!;

        public OrderGroupArgs()
        {
        }
        public static new OrderGroupArgs Empty => new OrderGroupArgs();
    }

    public sealed class OrderGroupState : global::Pulumi.ResourceArgs
    {
        [Input("bareMetalDevices")]
        private InputList<Inputs.OrderGroupBareMetalDeviceGetArgs>? _bareMetalDevices;

        /// <summary>
        /// A list of Bare Metal Devices to deploy
        /// </summary>
        public InputList<Inputs.OrderGroupBareMetalDeviceGetArgs> BareMetalDevices
        {
            get => _bareMetalDevices ?? (_bareMetalDevices = new InputList<Inputs.OrderGroupBareMetalDeviceGetArgs>());
            set => _bareMetalDevices = value;
        }

        /// <summary>
        /// Name of this Order Group
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Devices will be placed in the same rack
        /// </summary>
        [Input("sameRack")]
        public Input<bool>? SameRack { get; set; }

        public OrderGroupState()
        {
        }
        public static new OrderGroupState Empty => new OrderGroupState();
    }
}
