// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Hivelocity
{
    [HivelocityResourceType("hivelocity:index/sshKeyDetail:SshKeyDetail")]
    public partial class SshKeyDetail : global::Pulumi.CustomResource
    {
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("publicKey")]
        public Output<string> PublicKey { get; private set; } = null!;

        [Output("sshKeyId")]
        public Output<int> SshKeyId { get; private set; } = null!;


        /// <summary>
        /// Create a SshKeyDetail resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SshKeyDetail(string name, SshKeyDetailArgs args, CustomResourceOptions? options = null)
            : base("hivelocity:index/sshKeyDetail:SshKeyDetail", name, args ?? new SshKeyDetailArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SshKeyDetail(string name, Input<string> id, SshKeyDetailState? state = null, CustomResourceOptions? options = null)
            : base("hivelocity:index/sshKeyDetail:SshKeyDetail", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                Aliases =
                {
                    new global::Pulumi.Alias { Type = "hivelocity:index/sshKey:sshKey" },
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SshKeyDetail resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SshKeyDetail Get(string name, Input<string> id, SshKeyDetailState? state = null, CustomResourceOptions? options = null)
        {
            return new SshKeyDetail(name, id, state, options);
        }
    }

    public sealed class SshKeyDetailArgs : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("publicKey", required: true)]
        public Input<string> PublicKey { get; set; } = null!;

        [Input("sshKeyId")]
        public Input<int>? SshKeyId { get; set; }

        public SshKeyDetailArgs()
        {
        }
        public static new SshKeyDetailArgs Empty => new SshKeyDetailArgs();
    }

    public sealed class SshKeyDetailState : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("publicKey")]
        public Input<string>? PublicKey { get; set; }

        [Input("sshKeyId")]
        public Input<int>? SshKeyId { get; set; }

        public SshKeyDetailState()
        {
        }
        public static new SshKeyDetailState Empty => new SshKeyDetailState();
    }
}
