// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/embp/pulumi-hivelocity/sdk/go/hivelocity/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Your API Key from the https://my.hivelocity.net portal.
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "hivelocity:apiKey")
}

// The API instance to communicate with defaults to https://core.hivelocity.net/api/v2
func GetApiUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "hivelocity:apiUrl")
}
