# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .bare_metal_device import *
from .bare_metal_device_detail import *
from .get_bare_metal_device import *
from .get_device import *
from .get_device_initial_creds import *
from .get_device_port import *
from .get_effective_ignition import *
from .get_hivelocity_device_port import *
from .get_product import *
from .get_ssh_key import *
from .ignition import *
from .ignition_detail import *
from .order_group import *
from .order_group_detail import *
from .provider import *
from .ssh_key import *
from .ssh_key_detail import *
from .vlan import *
from .vlan_detail import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_hivelocity.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_hivelocity.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "hivelocity",
  "mod": "index/bareMetalDevice",
  "fqn": "pulumi_hivelocity",
  "classes": {
   "hivelocity:index/bareMetalDevice:bareMetalDevice": "BareMetalDevice"
  }
 },
 {
  "pkg": "hivelocity",
  "mod": "index/bareMetalDeviceDetail",
  "fqn": "pulumi_hivelocity",
  "classes": {
   "hivelocity:index/bareMetalDeviceDetail:BareMetalDeviceDetail": "BareMetalDeviceDetail"
  }
 },
 {
  "pkg": "hivelocity",
  "mod": "index/ignition",
  "fqn": "pulumi_hivelocity",
  "classes": {
   "hivelocity:index/ignition:ignition": "Ignition"
  }
 },
 {
  "pkg": "hivelocity",
  "mod": "index/ignitionDetail",
  "fqn": "pulumi_hivelocity",
  "classes": {
   "hivelocity:index/ignitionDetail:IgnitionDetail": "IgnitionDetail"
  }
 },
 {
  "pkg": "hivelocity",
  "mod": "index/orderGroup",
  "fqn": "pulumi_hivelocity",
  "classes": {
   "hivelocity:index/orderGroup:orderGroup": "OrderGroup"
  }
 },
 {
  "pkg": "hivelocity",
  "mod": "index/orderGroupDetail",
  "fqn": "pulumi_hivelocity",
  "classes": {
   "hivelocity:index/orderGroupDetail:OrderGroupDetail": "OrderGroupDetail"
  }
 },
 {
  "pkg": "hivelocity",
  "mod": "index/sshKey",
  "fqn": "pulumi_hivelocity",
  "classes": {
   "hivelocity:index/sshKey:sshKey": "SshKey"
  }
 },
 {
  "pkg": "hivelocity",
  "mod": "index/sshKeyDetail",
  "fqn": "pulumi_hivelocity",
  "classes": {
   "hivelocity:index/sshKeyDetail:SshKeyDetail": "SshKeyDetail"
  }
 },
 {
  "pkg": "hivelocity",
  "mod": "index/vlan",
  "fqn": "pulumi_hivelocity",
  "classes": {
   "hivelocity:index/vlan:vlan": "Vlan"
  }
 },
 {
  "pkg": "hivelocity",
  "mod": "index/vlanDetail",
  "fqn": "pulumi_hivelocity",
  "classes": {
   "hivelocity:index/vlanDetail:VlanDetail": "VlanDetail"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "hivelocity",
  "token": "pulumi:providers:hivelocity",
  "fqn": "pulumi_hivelocity",
  "class": "Provider"
 }
]
"""
)
