// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package hivelocity

import (
	"context"
	"reflect"

	"github.com/embp/pulumi-hivelocity/sdk/go/hivelocity/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDeviceInitialCreds(ctx *pulumi.Context, args *GetDeviceInitialCredsArgs, opts ...pulumi.InvokeOption) (*GetDeviceInitialCredsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDeviceInitialCredsResult
	err := ctx.Invoke("hivelocity:index/getDeviceInitialCreds:getDeviceInitialCreds", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDeviceInitialCreds.
type GetDeviceInitialCredsArgs struct {
	DeviceId int `pulumi:"deviceId"`
}

// A collection of values returned by getDeviceInitialCreds.
type GetDeviceInitialCredsResult struct {
	DeviceId int `pulumi:"deviceId"`
	// The provider-assigned unique ID for this managed resource.
	Id        string `pulumi:"id"`
	LockerUrl string `pulumi:"lockerUrl"`
	Password  string `pulumi:"password"`
	Port      int    `pulumi:"port"`
	User      string `pulumi:"user"`
}

func GetDeviceInitialCredsOutput(ctx *pulumi.Context, args GetDeviceInitialCredsOutputArgs, opts ...pulumi.InvokeOption) GetDeviceInitialCredsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDeviceInitialCredsResult, error) {
			args := v.(GetDeviceInitialCredsArgs)
			r, err := GetDeviceInitialCreds(ctx, &args, opts...)
			var s GetDeviceInitialCredsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetDeviceInitialCredsResultOutput)
}

// A collection of arguments for invoking getDeviceInitialCreds.
type GetDeviceInitialCredsOutputArgs struct {
	DeviceId pulumi.IntInput `pulumi:"deviceId"`
}

func (GetDeviceInitialCredsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDeviceInitialCredsArgs)(nil)).Elem()
}

// A collection of values returned by getDeviceInitialCreds.
type GetDeviceInitialCredsResultOutput struct{ *pulumi.OutputState }

func (GetDeviceInitialCredsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDeviceInitialCredsResult)(nil)).Elem()
}

func (o GetDeviceInitialCredsResultOutput) ToGetDeviceInitialCredsResultOutput() GetDeviceInitialCredsResultOutput {
	return o
}

func (o GetDeviceInitialCredsResultOutput) ToGetDeviceInitialCredsResultOutputWithContext(ctx context.Context) GetDeviceInitialCredsResultOutput {
	return o
}

func (o GetDeviceInitialCredsResultOutput) DeviceId() pulumi.IntOutput {
	return o.ApplyT(func(v GetDeviceInitialCredsResult) int { return v.DeviceId }).(pulumi.IntOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetDeviceInitialCredsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceInitialCredsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDeviceInitialCredsResultOutput) LockerUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceInitialCredsResult) string { return v.LockerUrl }).(pulumi.StringOutput)
}

func (o GetDeviceInitialCredsResultOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceInitialCredsResult) string { return v.Password }).(pulumi.StringOutput)
}

func (o GetDeviceInitialCredsResultOutput) Port() pulumi.IntOutput {
	return o.ApplyT(func(v GetDeviceInitialCredsResult) int { return v.Port }).(pulumi.IntOutput)
}

func (o GetDeviceInitialCredsResultOutput) User() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceInitialCredsResult) string { return v.User }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDeviceInitialCredsResultOutput{})
}
