// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package hivelocity

import (
	"context"
	"reflect"

	"github.com/embp/pulumi-hivelocity/sdk/go/hivelocity/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDevice(ctx *pulumi.Context, args *GetDeviceArgs, opts ...pulumi.InvokeOption) (*GetDeviceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDeviceResult
	err := ctx.Invoke("hivelocity:index/getDevice:getDevice", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDevice.
type GetDeviceArgs struct {
	Filters []GetDeviceFilter `pulumi:"filters"`
	First   *bool             `pulumi:"first"`
}

// A collection of values returned by getDevice.
type GetDeviceResult struct {
	DeviceId   int               `pulumi:"deviceId"`
	DeviceType string            `pulumi:"deviceType"`
	Filters    []GetDeviceFilter `pulumi:"filters"`
	First      *bool             `pulumi:"first"`
	Hostname   string            `pulumi:"hostname"`
	// The provider-assigned unique ID for this managed resource.
	Id          string            `pulumi:"id"`
	IpAddresses []string          `pulumi:"ipAddresses"`
	IpmiAddress string            `pulumi:"ipmiAddress"`
	IpmiEnabled bool              `pulumi:"ipmiEnabled"`
	Location    map[string]string `pulumi:"location"`
	Metadata    map[string]string `pulumi:"metadata"`
	Name        string            `pulumi:"name"`
	PowerStatus string            `pulumi:"powerStatus"`
	ServicePlan int               `pulumi:"servicePlan"`
	Status      string            `pulumi:"status"`
	Tags        []string          `pulumi:"tags"`
}

func GetDeviceOutput(ctx *pulumi.Context, args GetDeviceOutputArgs, opts ...pulumi.InvokeOption) GetDeviceResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDeviceResult, error) {
			args := v.(GetDeviceArgs)
			r, err := GetDevice(ctx, &args, opts...)
			var s GetDeviceResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetDeviceResultOutput)
}

// A collection of arguments for invoking getDevice.
type GetDeviceOutputArgs struct {
	Filters GetDeviceFilterArrayInput `pulumi:"filters"`
	First   pulumi.BoolPtrInput       `pulumi:"first"`
}

func (GetDeviceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDeviceArgs)(nil)).Elem()
}

// A collection of values returned by getDevice.
type GetDeviceResultOutput struct{ *pulumi.OutputState }

func (GetDeviceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDeviceResult)(nil)).Elem()
}

func (o GetDeviceResultOutput) ToGetDeviceResultOutput() GetDeviceResultOutput {
	return o
}

func (o GetDeviceResultOutput) ToGetDeviceResultOutputWithContext(ctx context.Context) GetDeviceResultOutput {
	return o
}

func (o GetDeviceResultOutput) DeviceId() pulumi.IntOutput {
	return o.ApplyT(func(v GetDeviceResult) int { return v.DeviceId }).(pulumi.IntOutput)
}

func (o GetDeviceResultOutput) DeviceType() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.DeviceType }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) Filters() GetDeviceFilterArrayOutput {
	return o.ApplyT(func(v GetDeviceResult) []GetDeviceFilter { return v.Filters }).(GetDeviceFilterArrayOutput)
}

func (o GetDeviceResultOutput) First() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetDeviceResult) *bool { return v.First }).(pulumi.BoolPtrOutput)
}

func (o GetDeviceResultOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.Hostname }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetDeviceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) IpAddresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetDeviceResult) []string { return v.IpAddresses }).(pulumi.StringArrayOutput)
}

func (o GetDeviceResultOutput) IpmiAddress() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.IpmiAddress }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) IpmiEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDeviceResult) bool { return v.IpmiEnabled }).(pulumi.BoolOutput)
}

func (o GetDeviceResultOutput) Location() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetDeviceResult) map[string]string { return v.Location }).(pulumi.StringMapOutput)
}

func (o GetDeviceResultOutput) Metadata() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetDeviceResult) map[string]string { return v.Metadata }).(pulumi.StringMapOutput)
}

func (o GetDeviceResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) PowerStatus() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.PowerStatus }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) ServicePlan() pulumi.IntOutput {
	return o.ApplyT(func(v GetDeviceResult) int { return v.ServicePlan }).(pulumi.IntOutput)
}

func (o GetDeviceResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetDeviceResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDeviceResultOutput{})
}
