// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package hivelocity

import (
	"context"
	"reflect"

	"github.com/embp/pulumi-hivelocity/sdk/go/hivelocity/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDevicePort(ctx *pulumi.Context, args *GetDevicePortArgs, opts ...pulumi.InvokeOption) (*GetDevicePortResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDevicePortResult
	err := ctx.Invoke("hivelocity:index/getDevicePort:getDevicePort", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDevicePort.
type GetDevicePortArgs struct {
	DeviceId int                   `pulumi:"deviceId"`
	Filters  []GetDevicePortFilter `pulumi:"filters"`
	First    *bool                 `pulumi:"first"`
}

// A collection of values returned by getDevicePort.
type GetDevicePortResult struct {
	DeviceId int                   `pulumi:"deviceId"`
	Filters  []GetDevicePortFilter `pulumi:"filters"`
	First    *bool                 `pulumi:"first"`
	// The provider-assigned unique ID for this managed resource.
	Id      string `pulumi:"id"`
	IsBond  bool   `pulumi:"isBond"`
	Name    string `pulumi:"name"`
	PortId  int    `pulumi:"portId"`
	Private bool   `pulumi:"private"`
}

func GetDevicePortOutput(ctx *pulumi.Context, args GetDevicePortOutputArgs, opts ...pulumi.InvokeOption) GetDevicePortResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDevicePortResult, error) {
			args := v.(GetDevicePortArgs)
			r, err := GetDevicePort(ctx, &args, opts...)
			var s GetDevicePortResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetDevicePortResultOutput)
}

// A collection of arguments for invoking getDevicePort.
type GetDevicePortOutputArgs struct {
	DeviceId pulumi.IntInput               `pulumi:"deviceId"`
	Filters  GetDevicePortFilterArrayInput `pulumi:"filters"`
	First    pulumi.BoolPtrInput           `pulumi:"first"`
}

func (GetDevicePortOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDevicePortArgs)(nil)).Elem()
}

// A collection of values returned by getDevicePort.
type GetDevicePortResultOutput struct{ *pulumi.OutputState }

func (GetDevicePortResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDevicePortResult)(nil)).Elem()
}

func (o GetDevicePortResultOutput) ToGetDevicePortResultOutput() GetDevicePortResultOutput {
	return o
}

func (o GetDevicePortResultOutput) ToGetDevicePortResultOutputWithContext(ctx context.Context) GetDevicePortResultOutput {
	return o
}

func (o GetDevicePortResultOutput) DeviceId() pulumi.IntOutput {
	return o.ApplyT(func(v GetDevicePortResult) int { return v.DeviceId }).(pulumi.IntOutput)
}

func (o GetDevicePortResultOutput) Filters() GetDevicePortFilterArrayOutput {
	return o.ApplyT(func(v GetDevicePortResult) []GetDevicePortFilter { return v.Filters }).(GetDevicePortFilterArrayOutput)
}

func (o GetDevicePortResultOutput) First() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetDevicePortResult) *bool { return v.First }).(pulumi.BoolPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetDevicePortResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDevicePortResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDevicePortResultOutput) IsBond() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDevicePortResult) bool { return v.IsBond }).(pulumi.BoolOutput)
}

func (o GetDevicePortResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetDevicePortResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetDevicePortResultOutput) PortId() pulumi.IntOutput {
	return o.ApplyT(func(v GetDevicePortResult) int { return v.PortId }).(pulumi.IntOutput)
}

func (o GetDevicePortResultOutput) Private() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDevicePortResult) bool { return v.Private }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDevicePortResultOutput{})
}
