// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package hivelocity

import (
	"context"
	"reflect"

	"github.com/embp/pulumi-hivelocity/sdk/go/hivelocity/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetProduct(ctx *pulumi.Context, args *GetProductArgs, opts ...pulumi.InvokeOption) (*GetProductResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetProductResult
	err := ctx.Invoke("hivelocity:index/getProduct:getProduct", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getProduct.
type GetProductArgs struct {
	Filters []GetProductFilter `pulumi:"filters"`
	First   *bool              `pulumi:"first"`
}

// A collection of values returned by getProduct.
type GetProductResult struct {
	AnnuallyLocationPremium float64            `pulumi:"annuallyLocationPremium"`
	BiennialLocationPremium float64            `pulumi:"biennialLocationPremium"`
	Core                    bool               `pulumi:"core"`
	DataCenter              string             `pulumi:"dataCenter"`
	Edge                    bool               `pulumi:"edge"`
	Filters                 []GetProductFilter `pulumi:"filters"`
	First                   *bool              `pulumi:"first"`
	HourlyLocationPremium   float64            `pulumi:"hourlyLocationPremium"`
	// The provider-assigned unique ID for this managed resource.
	Id                            string   `pulumi:"id"`
	MonthlyLocationPremium        float64  `pulumi:"monthlyLocationPremium"`
	ProductAnnuallyPrice          float64  `pulumi:"productAnnuallyPrice"`
	ProductBandwidth              string   `pulumi:"productBandwidth"`
	ProductBiennialPrice          float64  `pulumi:"productBiennialPrice"`
	ProductCpu                    string   `pulumi:"productCpu"`
	ProductCpuCores               string   `pulumi:"productCpuCores"`
	ProductDisabledBillingPeriods []string `pulumi:"productDisabledBillingPeriods"`
	ProductDisplayPrice           float64  `pulumi:"productDisplayPrice"`
	ProductDrive                  string   `pulumi:"productDrive"`
	ProductGpu                    string   `pulumi:"productGpu"`
	ProductHourlyPrice            float64  `pulumi:"productHourlyPrice"`
	ProductId                     int      `pulumi:"productId"`
	ProductMemory                 string   `pulumi:"productMemory"`
	ProductMonthlyPrice           float64  `pulumi:"productMonthlyPrice"`
	ProductName                   string   `pulumi:"productName"`
	ProductOnSale                 bool     `pulumi:"productOnSale"`
	ProductOriginalPrice          float64  `pulumi:"productOriginalPrice"`
	ProductQuarterlyPrice         float64  `pulumi:"productQuarterlyPrice"`
	ProductSemiAnnuallyPrice      float64  `pulumi:"productSemiAnnuallyPrice"`
	ProductTriennialPrice         float64  `pulumi:"productTriennialPrice"`
	QuarterlyLocationPremium      float64  `pulumi:"quarterlyLocationPremium"`
	SemiAnnuallyLocationPremium   float64  `pulumi:"semiAnnuallyLocationPremium"`
	Stock                         string   `pulumi:"stock"`
	TriennialLocationPremium      float64  `pulumi:"triennialLocationPremium"`
}

func GetProductOutput(ctx *pulumi.Context, args GetProductOutputArgs, opts ...pulumi.InvokeOption) GetProductResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetProductResult, error) {
			args := v.(GetProductArgs)
			r, err := GetProduct(ctx, &args, opts...)
			var s GetProductResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetProductResultOutput)
}

// A collection of arguments for invoking getProduct.
type GetProductOutputArgs struct {
	Filters GetProductFilterArrayInput `pulumi:"filters"`
	First   pulumi.BoolPtrInput        `pulumi:"first"`
}

func (GetProductOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProductArgs)(nil)).Elem()
}

// A collection of values returned by getProduct.
type GetProductResultOutput struct{ *pulumi.OutputState }

func (GetProductResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProductResult)(nil)).Elem()
}

func (o GetProductResultOutput) ToGetProductResultOutput() GetProductResultOutput {
	return o
}

func (o GetProductResultOutput) ToGetProductResultOutputWithContext(ctx context.Context) GetProductResultOutput {
	return o
}

func (o GetProductResultOutput) AnnuallyLocationPremium() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.AnnuallyLocationPremium }).(pulumi.Float64Output)
}

func (o GetProductResultOutput) BiennialLocationPremium() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.BiennialLocationPremium }).(pulumi.Float64Output)
}

func (o GetProductResultOutput) Core() pulumi.BoolOutput {
	return o.ApplyT(func(v GetProductResult) bool { return v.Core }).(pulumi.BoolOutput)
}

func (o GetProductResultOutput) DataCenter() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductResult) string { return v.DataCenter }).(pulumi.StringOutput)
}

func (o GetProductResultOutput) Edge() pulumi.BoolOutput {
	return o.ApplyT(func(v GetProductResult) bool { return v.Edge }).(pulumi.BoolOutput)
}

func (o GetProductResultOutput) Filters() GetProductFilterArrayOutput {
	return o.ApplyT(func(v GetProductResult) []GetProductFilter { return v.Filters }).(GetProductFilterArrayOutput)
}

func (o GetProductResultOutput) First() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetProductResult) *bool { return v.First }).(pulumi.BoolPtrOutput)
}

func (o GetProductResultOutput) HourlyLocationPremium() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.HourlyLocationPremium }).(pulumi.Float64Output)
}

// The provider-assigned unique ID for this managed resource.
func (o GetProductResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetProductResultOutput) MonthlyLocationPremium() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.MonthlyLocationPremium }).(pulumi.Float64Output)
}

func (o GetProductResultOutput) ProductAnnuallyPrice() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.ProductAnnuallyPrice }).(pulumi.Float64Output)
}

func (o GetProductResultOutput) ProductBandwidth() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductResult) string { return v.ProductBandwidth }).(pulumi.StringOutput)
}

func (o GetProductResultOutput) ProductBiennialPrice() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.ProductBiennialPrice }).(pulumi.Float64Output)
}

func (o GetProductResultOutput) ProductCpu() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductResult) string { return v.ProductCpu }).(pulumi.StringOutput)
}

func (o GetProductResultOutput) ProductCpuCores() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductResult) string { return v.ProductCpuCores }).(pulumi.StringOutput)
}

func (o GetProductResultOutput) ProductDisabledBillingPeriods() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetProductResult) []string { return v.ProductDisabledBillingPeriods }).(pulumi.StringArrayOutput)
}

func (o GetProductResultOutput) ProductDisplayPrice() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.ProductDisplayPrice }).(pulumi.Float64Output)
}

func (o GetProductResultOutput) ProductDrive() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductResult) string { return v.ProductDrive }).(pulumi.StringOutput)
}

func (o GetProductResultOutput) ProductGpu() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductResult) string { return v.ProductGpu }).(pulumi.StringOutput)
}

func (o GetProductResultOutput) ProductHourlyPrice() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.ProductHourlyPrice }).(pulumi.Float64Output)
}

func (o GetProductResultOutput) ProductId() pulumi.IntOutput {
	return o.ApplyT(func(v GetProductResult) int { return v.ProductId }).(pulumi.IntOutput)
}

func (o GetProductResultOutput) ProductMemory() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductResult) string { return v.ProductMemory }).(pulumi.StringOutput)
}

func (o GetProductResultOutput) ProductMonthlyPrice() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.ProductMonthlyPrice }).(pulumi.Float64Output)
}

func (o GetProductResultOutput) ProductName() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductResult) string { return v.ProductName }).(pulumi.StringOutput)
}

func (o GetProductResultOutput) ProductOnSale() pulumi.BoolOutput {
	return o.ApplyT(func(v GetProductResult) bool { return v.ProductOnSale }).(pulumi.BoolOutput)
}

func (o GetProductResultOutput) ProductOriginalPrice() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.ProductOriginalPrice }).(pulumi.Float64Output)
}

func (o GetProductResultOutput) ProductQuarterlyPrice() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.ProductQuarterlyPrice }).(pulumi.Float64Output)
}

func (o GetProductResultOutput) ProductSemiAnnuallyPrice() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.ProductSemiAnnuallyPrice }).(pulumi.Float64Output)
}

func (o GetProductResultOutput) ProductTriennialPrice() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.ProductTriennialPrice }).(pulumi.Float64Output)
}

func (o GetProductResultOutput) QuarterlyLocationPremium() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.QuarterlyLocationPremium }).(pulumi.Float64Output)
}

func (o GetProductResultOutput) SemiAnnuallyLocationPremium() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.SemiAnnuallyLocationPremium }).(pulumi.Float64Output)
}

func (o GetProductResultOutput) Stock() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductResult) string { return v.Stock }).(pulumi.StringOutput)
}

func (o GetProductResultOutput) TriennialLocationPremium() pulumi.Float64Output {
	return o.ApplyT(func(v GetProductResult) float64 { return v.TriennialLocationPremium }).(pulumi.Float64Output)
}

func init() {
	pulumi.RegisterOutputType(GetProductResultOutput{})
}
