// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package hivelocity

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/embp/pulumi-hivelocity/sdk/go/hivelocity/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "hivelocity:index/bareMetalDevice:bareMetalDevice":
		r = &BareMetalDevice{}
	case "hivelocity:index/bareMetalDeviceDetail:BareMetalDeviceDetail":
		r = &BareMetalDeviceDetail{}
	case "hivelocity:index/ignition:ignition":
		r = &Ignition{}
	case "hivelocity:index/ignitionDetail:IgnitionDetail":
		r = &IgnitionDetail{}
	case "hivelocity:index/orderGroup:orderGroup":
		r = &OrderGroup{}
	case "hivelocity:index/orderGroupDetail:OrderGroupDetail":
		r = &OrderGroupDetail{}
	case "hivelocity:index/sshKey:sshKey":
		r = &SshKey{}
	case "hivelocity:index/sshKeyDetail:SshKeyDetail":
		r = &SshKeyDetail{}
	case "hivelocity:index/vlan:vlan":
		r = &Vlan{}
	case "hivelocity:index/vlanDetail:VlanDetail":
		r = &VlanDetail{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:hivelocity" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"hivelocity",
		"index/bareMetalDevice",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"hivelocity",
		"index/bareMetalDeviceDetail",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"hivelocity",
		"index/ignition",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"hivelocity",
		"index/ignitionDetail",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"hivelocity",
		"index/orderGroup",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"hivelocity",
		"index/orderGroupDetail",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"hivelocity",
		"index/sshKey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"hivelocity",
		"index/sshKeyDetail",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"hivelocity",
		"index/vlan",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"hivelocity",
		"index/vlanDetail",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"hivelocity",
		&pkg{version},
	)
}
