// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package hivelocity

import (
	"context"
	"reflect"

	"github.com/embp/pulumi-hivelocity/sdk/go/hivelocity/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type OrderGroupDetailBareMetalDevice struct {
	// When set, prefer only bonded devices
	Bonded *bool `pulumi:"bonded"`
	// Device ID
	DeviceId *int `pulumi:"deviceId"`
	// Force deployment of this Device ID (internal use only)
	ForceDeviceId *int `pulumi:"forceDeviceId"`
	// Hostname for this device
	Hostname string `pulumi:"hostname"`
	// IgnitionConfig ID
	IgnitionId *int `pulumi:"ignitionId"`
	// Last time this device was updated
	LastUpdated *string `pulumi:"lastUpdated"`
	// Deploy device in this location
	LocationName string `pulumi:"locationName"`
	// Order ID
	OrderId *int `pulumi:"orderId"`
	// Operating system to install on device
	OsName string `pulumi:"osName"`
	// Billing period for device
	Period *string `pulumi:"period"`
	// Power status
	PowerStatus *string `pulumi:"powerStatus"`
	// Primary IP of device
	PrimaryIp *string `pulumi:"primaryIp"`
	// Product ID to pick from the stock
	ProductId int `pulumi:"productId"`
	// Product Name
	ProductName *string `pulumi:"productName"`
	// ID of a SSH Key to apply for device
	PublicSshKeyId *int `pulumi:"publicSshKeyId"`
	// Post-install script for device
	Script *string `pulumi:"script"`
	// Service ID
	ServiceId *int `pulumi:"serviceId"`
	// Tags to apply for device
	Tags []string `pulumi:"tags"`
	// VLAN ID
	//
	// Deprecated: This field is deprecated. Please use a VlanDetail resource instead.
	VlanId *int `pulumi:"vlanId"`
}

// OrderGroupDetailBareMetalDeviceInput is an input type that accepts OrderGroupDetailBareMetalDeviceArgs and OrderGroupDetailBareMetalDeviceOutput values.
// You can construct a concrete instance of `OrderGroupDetailBareMetalDeviceInput` via:
//
//	OrderGroupDetailBareMetalDeviceArgs{...}
type OrderGroupDetailBareMetalDeviceInput interface {
	pulumi.Input

	ToOrderGroupDetailBareMetalDeviceOutput() OrderGroupDetailBareMetalDeviceOutput
	ToOrderGroupDetailBareMetalDeviceOutputWithContext(context.Context) OrderGroupDetailBareMetalDeviceOutput
}

type OrderGroupDetailBareMetalDeviceArgs struct {
	// When set, prefer only bonded devices
	Bonded pulumi.BoolPtrInput `pulumi:"bonded"`
	// Device ID
	DeviceId pulumi.IntPtrInput `pulumi:"deviceId"`
	// Force deployment of this Device ID (internal use only)
	ForceDeviceId pulumi.IntPtrInput `pulumi:"forceDeviceId"`
	// Hostname for this device
	Hostname pulumi.StringInput `pulumi:"hostname"`
	// IgnitionConfig ID
	IgnitionId pulumi.IntPtrInput `pulumi:"ignitionId"`
	// Last time this device was updated
	LastUpdated pulumi.StringPtrInput `pulumi:"lastUpdated"`
	// Deploy device in this location
	LocationName pulumi.StringInput `pulumi:"locationName"`
	// Order ID
	OrderId pulumi.IntPtrInput `pulumi:"orderId"`
	// Operating system to install on device
	OsName pulumi.StringInput `pulumi:"osName"`
	// Billing period for device
	Period pulumi.StringPtrInput `pulumi:"period"`
	// Power status
	PowerStatus pulumi.StringPtrInput `pulumi:"powerStatus"`
	// Primary IP of device
	PrimaryIp pulumi.StringPtrInput `pulumi:"primaryIp"`
	// Product ID to pick from the stock
	ProductId pulumi.IntInput `pulumi:"productId"`
	// Product Name
	ProductName pulumi.StringPtrInput `pulumi:"productName"`
	// ID of a SSH Key to apply for device
	PublicSshKeyId pulumi.IntPtrInput `pulumi:"publicSshKeyId"`
	// Post-install script for device
	Script pulumi.StringPtrInput `pulumi:"script"`
	// Service ID
	ServiceId pulumi.IntPtrInput `pulumi:"serviceId"`
	// Tags to apply for device
	Tags pulumi.StringArrayInput `pulumi:"tags"`
	// VLAN ID
	//
	// Deprecated: This field is deprecated. Please use a VlanDetail resource instead.
	VlanId pulumi.IntPtrInput `pulumi:"vlanId"`
}

func (OrderGroupDetailBareMetalDeviceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*OrderGroupDetailBareMetalDevice)(nil)).Elem()
}

func (i OrderGroupDetailBareMetalDeviceArgs) ToOrderGroupDetailBareMetalDeviceOutput() OrderGroupDetailBareMetalDeviceOutput {
	return i.ToOrderGroupDetailBareMetalDeviceOutputWithContext(context.Background())
}

func (i OrderGroupDetailBareMetalDeviceArgs) ToOrderGroupDetailBareMetalDeviceOutputWithContext(ctx context.Context) OrderGroupDetailBareMetalDeviceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrderGroupDetailBareMetalDeviceOutput)
}

// OrderGroupDetailBareMetalDeviceArrayInput is an input type that accepts OrderGroupDetailBareMetalDeviceArray and OrderGroupDetailBareMetalDeviceArrayOutput values.
// You can construct a concrete instance of `OrderGroupDetailBareMetalDeviceArrayInput` via:
//
//	OrderGroupDetailBareMetalDeviceArray{ OrderGroupDetailBareMetalDeviceArgs{...} }
type OrderGroupDetailBareMetalDeviceArrayInput interface {
	pulumi.Input

	ToOrderGroupDetailBareMetalDeviceArrayOutput() OrderGroupDetailBareMetalDeviceArrayOutput
	ToOrderGroupDetailBareMetalDeviceArrayOutputWithContext(context.Context) OrderGroupDetailBareMetalDeviceArrayOutput
}

type OrderGroupDetailBareMetalDeviceArray []OrderGroupDetailBareMetalDeviceInput

func (OrderGroupDetailBareMetalDeviceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]OrderGroupDetailBareMetalDevice)(nil)).Elem()
}

func (i OrderGroupDetailBareMetalDeviceArray) ToOrderGroupDetailBareMetalDeviceArrayOutput() OrderGroupDetailBareMetalDeviceArrayOutput {
	return i.ToOrderGroupDetailBareMetalDeviceArrayOutputWithContext(context.Background())
}

func (i OrderGroupDetailBareMetalDeviceArray) ToOrderGroupDetailBareMetalDeviceArrayOutputWithContext(ctx context.Context) OrderGroupDetailBareMetalDeviceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrderGroupDetailBareMetalDeviceArrayOutput)
}

type OrderGroupDetailBareMetalDeviceOutput struct{ *pulumi.OutputState }

func (OrderGroupDetailBareMetalDeviceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*OrderGroupDetailBareMetalDevice)(nil)).Elem()
}

func (o OrderGroupDetailBareMetalDeviceOutput) ToOrderGroupDetailBareMetalDeviceOutput() OrderGroupDetailBareMetalDeviceOutput {
	return o
}

func (o OrderGroupDetailBareMetalDeviceOutput) ToOrderGroupDetailBareMetalDeviceOutputWithContext(ctx context.Context) OrderGroupDetailBareMetalDeviceOutput {
	return o
}

// When set, prefer only bonded devices
func (o OrderGroupDetailBareMetalDeviceOutput) Bonded() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) *bool { return v.Bonded }).(pulumi.BoolPtrOutput)
}

// Device ID
func (o OrderGroupDetailBareMetalDeviceOutput) DeviceId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) *int { return v.DeviceId }).(pulumi.IntPtrOutput)
}

// Force deployment of this Device ID (internal use only)
func (o OrderGroupDetailBareMetalDeviceOutput) ForceDeviceId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) *int { return v.ForceDeviceId }).(pulumi.IntPtrOutput)
}

// Hostname for this device
func (o OrderGroupDetailBareMetalDeviceOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) string { return v.Hostname }).(pulumi.StringOutput)
}

// IgnitionConfig ID
func (o OrderGroupDetailBareMetalDeviceOutput) IgnitionId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) *int { return v.IgnitionId }).(pulumi.IntPtrOutput)
}

// Last time this device was updated
func (o OrderGroupDetailBareMetalDeviceOutput) LastUpdated() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) *string { return v.LastUpdated }).(pulumi.StringPtrOutput)
}

// Deploy device in this location
func (o OrderGroupDetailBareMetalDeviceOutput) LocationName() pulumi.StringOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) string { return v.LocationName }).(pulumi.StringOutput)
}

// Order ID
func (o OrderGroupDetailBareMetalDeviceOutput) OrderId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) *int { return v.OrderId }).(pulumi.IntPtrOutput)
}

// Operating system to install on device
func (o OrderGroupDetailBareMetalDeviceOutput) OsName() pulumi.StringOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) string { return v.OsName }).(pulumi.StringOutput)
}

// Billing period for device
func (o OrderGroupDetailBareMetalDeviceOutput) Period() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) *string { return v.Period }).(pulumi.StringPtrOutput)
}

// Power status
func (o OrderGroupDetailBareMetalDeviceOutput) PowerStatus() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) *string { return v.PowerStatus }).(pulumi.StringPtrOutput)
}

// Primary IP of device
func (o OrderGroupDetailBareMetalDeviceOutput) PrimaryIp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) *string { return v.PrimaryIp }).(pulumi.StringPtrOutput)
}

// Product ID to pick from the stock
func (o OrderGroupDetailBareMetalDeviceOutput) ProductId() pulumi.IntOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) int { return v.ProductId }).(pulumi.IntOutput)
}

// Product Name
func (o OrderGroupDetailBareMetalDeviceOutput) ProductName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) *string { return v.ProductName }).(pulumi.StringPtrOutput)
}

// ID of a SSH Key to apply for device
func (o OrderGroupDetailBareMetalDeviceOutput) PublicSshKeyId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) *int { return v.PublicSshKeyId }).(pulumi.IntPtrOutput)
}

// Post-install script for device
func (o OrderGroupDetailBareMetalDeviceOutput) Script() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) *string { return v.Script }).(pulumi.StringPtrOutput)
}

// Service ID
func (o OrderGroupDetailBareMetalDeviceOutput) ServiceId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) *int { return v.ServiceId }).(pulumi.IntPtrOutput)
}

// Tags to apply for device
func (o OrderGroupDetailBareMetalDeviceOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

// VLAN ID
//
// Deprecated: This field is deprecated. Please use a VlanDetail resource instead.
func (o OrderGroupDetailBareMetalDeviceOutput) VlanId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v OrderGroupDetailBareMetalDevice) *int { return v.VlanId }).(pulumi.IntPtrOutput)
}

type OrderGroupDetailBareMetalDeviceArrayOutput struct{ *pulumi.OutputState }

func (OrderGroupDetailBareMetalDeviceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]OrderGroupDetailBareMetalDevice)(nil)).Elem()
}

func (o OrderGroupDetailBareMetalDeviceArrayOutput) ToOrderGroupDetailBareMetalDeviceArrayOutput() OrderGroupDetailBareMetalDeviceArrayOutput {
	return o
}

func (o OrderGroupDetailBareMetalDeviceArrayOutput) ToOrderGroupDetailBareMetalDeviceArrayOutputWithContext(ctx context.Context) OrderGroupDetailBareMetalDeviceArrayOutput {
	return o
}

func (o OrderGroupDetailBareMetalDeviceArrayOutput) Index(i pulumi.IntInput) OrderGroupDetailBareMetalDeviceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) OrderGroupDetailBareMetalDevice {
		return vs[0].([]OrderGroupDetailBareMetalDevice)[vs[1].(int)]
	}).(OrderGroupDetailBareMetalDeviceOutput)
}

type GetBareMetalDeviceFilter struct {
	Name   string   `pulumi:"name"`
	Values []string `pulumi:"values"`
}

// GetBareMetalDeviceFilterInput is an input type that accepts GetBareMetalDeviceFilterArgs and GetBareMetalDeviceFilterOutput values.
// You can construct a concrete instance of `GetBareMetalDeviceFilterInput` via:
//
//	GetBareMetalDeviceFilterArgs{...}
type GetBareMetalDeviceFilterInput interface {
	pulumi.Input

	ToGetBareMetalDeviceFilterOutput() GetBareMetalDeviceFilterOutput
	ToGetBareMetalDeviceFilterOutputWithContext(context.Context) GetBareMetalDeviceFilterOutput
}

type GetBareMetalDeviceFilterArgs struct {
	Name   pulumi.StringInput      `pulumi:"name"`
	Values pulumi.StringArrayInput `pulumi:"values"`
}

func (GetBareMetalDeviceFilterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBareMetalDeviceFilter)(nil)).Elem()
}

func (i GetBareMetalDeviceFilterArgs) ToGetBareMetalDeviceFilterOutput() GetBareMetalDeviceFilterOutput {
	return i.ToGetBareMetalDeviceFilterOutputWithContext(context.Background())
}

func (i GetBareMetalDeviceFilterArgs) ToGetBareMetalDeviceFilterOutputWithContext(ctx context.Context) GetBareMetalDeviceFilterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetBareMetalDeviceFilterOutput)
}

// GetBareMetalDeviceFilterArrayInput is an input type that accepts GetBareMetalDeviceFilterArray and GetBareMetalDeviceFilterArrayOutput values.
// You can construct a concrete instance of `GetBareMetalDeviceFilterArrayInput` via:
//
//	GetBareMetalDeviceFilterArray{ GetBareMetalDeviceFilterArgs{...} }
type GetBareMetalDeviceFilterArrayInput interface {
	pulumi.Input

	ToGetBareMetalDeviceFilterArrayOutput() GetBareMetalDeviceFilterArrayOutput
	ToGetBareMetalDeviceFilterArrayOutputWithContext(context.Context) GetBareMetalDeviceFilterArrayOutput
}

type GetBareMetalDeviceFilterArray []GetBareMetalDeviceFilterInput

func (GetBareMetalDeviceFilterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetBareMetalDeviceFilter)(nil)).Elem()
}

func (i GetBareMetalDeviceFilterArray) ToGetBareMetalDeviceFilterArrayOutput() GetBareMetalDeviceFilterArrayOutput {
	return i.ToGetBareMetalDeviceFilterArrayOutputWithContext(context.Background())
}

func (i GetBareMetalDeviceFilterArray) ToGetBareMetalDeviceFilterArrayOutputWithContext(ctx context.Context) GetBareMetalDeviceFilterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetBareMetalDeviceFilterArrayOutput)
}

type GetBareMetalDeviceFilterOutput struct{ *pulumi.OutputState }

func (GetBareMetalDeviceFilterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBareMetalDeviceFilter)(nil)).Elem()
}

func (o GetBareMetalDeviceFilterOutput) ToGetBareMetalDeviceFilterOutput() GetBareMetalDeviceFilterOutput {
	return o
}

func (o GetBareMetalDeviceFilterOutput) ToGetBareMetalDeviceFilterOutputWithContext(ctx context.Context) GetBareMetalDeviceFilterOutput {
	return o
}

func (o GetBareMetalDeviceFilterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetBareMetalDeviceFilter) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetBareMetalDeviceFilterOutput) Values() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetBareMetalDeviceFilter) []string { return v.Values }).(pulumi.StringArrayOutput)
}

type GetBareMetalDeviceFilterArrayOutput struct{ *pulumi.OutputState }

func (GetBareMetalDeviceFilterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetBareMetalDeviceFilter)(nil)).Elem()
}

func (o GetBareMetalDeviceFilterArrayOutput) ToGetBareMetalDeviceFilterArrayOutput() GetBareMetalDeviceFilterArrayOutput {
	return o
}

func (o GetBareMetalDeviceFilterArrayOutput) ToGetBareMetalDeviceFilterArrayOutputWithContext(ctx context.Context) GetBareMetalDeviceFilterArrayOutput {
	return o
}

func (o GetBareMetalDeviceFilterArrayOutput) Index(i pulumi.IntInput) GetBareMetalDeviceFilterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetBareMetalDeviceFilter {
		return vs[0].([]GetBareMetalDeviceFilter)[vs[1].(int)]
	}).(GetBareMetalDeviceFilterOutput)
}

type GetDeviceFilter struct {
	Name   string   `pulumi:"name"`
	Values []string `pulumi:"values"`
}

// GetDeviceFilterInput is an input type that accepts GetDeviceFilterArgs and GetDeviceFilterOutput values.
// You can construct a concrete instance of `GetDeviceFilterInput` via:
//
//	GetDeviceFilterArgs{...}
type GetDeviceFilterInput interface {
	pulumi.Input

	ToGetDeviceFilterOutput() GetDeviceFilterOutput
	ToGetDeviceFilterOutputWithContext(context.Context) GetDeviceFilterOutput
}

type GetDeviceFilterArgs struct {
	Name   pulumi.StringInput      `pulumi:"name"`
	Values pulumi.StringArrayInput `pulumi:"values"`
}

func (GetDeviceFilterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDeviceFilter)(nil)).Elem()
}

func (i GetDeviceFilterArgs) ToGetDeviceFilterOutput() GetDeviceFilterOutput {
	return i.ToGetDeviceFilterOutputWithContext(context.Background())
}

func (i GetDeviceFilterArgs) ToGetDeviceFilterOutputWithContext(ctx context.Context) GetDeviceFilterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetDeviceFilterOutput)
}

// GetDeviceFilterArrayInput is an input type that accepts GetDeviceFilterArray and GetDeviceFilterArrayOutput values.
// You can construct a concrete instance of `GetDeviceFilterArrayInput` via:
//
//	GetDeviceFilterArray{ GetDeviceFilterArgs{...} }
type GetDeviceFilterArrayInput interface {
	pulumi.Input

	ToGetDeviceFilterArrayOutput() GetDeviceFilterArrayOutput
	ToGetDeviceFilterArrayOutputWithContext(context.Context) GetDeviceFilterArrayOutput
}

type GetDeviceFilterArray []GetDeviceFilterInput

func (GetDeviceFilterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetDeviceFilter)(nil)).Elem()
}

func (i GetDeviceFilterArray) ToGetDeviceFilterArrayOutput() GetDeviceFilterArrayOutput {
	return i.ToGetDeviceFilterArrayOutputWithContext(context.Background())
}

func (i GetDeviceFilterArray) ToGetDeviceFilterArrayOutputWithContext(ctx context.Context) GetDeviceFilterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetDeviceFilterArrayOutput)
}

type GetDeviceFilterOutput struct{ *pulumi.OutputState }

func (GetDeviceFilterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDeviceFilter)(nil)).Elem()
}

func (o GetDeviceFilterOutput) ToGetDeviceFilterOutput() GetDeviceFilterOutput {
	return o
}

func (o GetDeviceFilterOutput) ToGetDeviceFilterOutputWithContext(ctx context.Context) GetDeviceFilterOutput {
	return o
}

func (o GetDeviceFilterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceFilter) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetDeviceFilterOutput) Values() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetDeviceFilter) []string { return v.Values }).(pulumi.StringArrayOutput)
}

type GetDeviceFilterArrayOutput struct{ *pulumi.OutputState }

func (GetDeviceFilterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetDeviceFilter)(nil)).Elem()
}

func (o GetDeviceFilterArrayOutput) ToGetDeviceFilterArrayOutput() GetDeviceFilterArrayOutput {
	return o
}

func (o GetDeviceFilterArrayOutput) ToGetDeviceFilterArrayOutputWithContext(ctx context.Context) GetDeviceFilterArrayOutput {
	return o
}

func (o GetDeviceFilterArrayOutput) Index(i pulumi.IntInput) GetDeviceFilterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetDeviceFilter {
		return vs[0].([]GetDeviceFilter)[vs[1].(int)]
	}).(GetDeviceFilterOutput)
}

type GetDevicePortFilter struct {
	Name   string   `pulumi:"name"`
	Values []string `pulumi:"values"`
}

// GetDevicePortFilterInput is an input type that accepts GetDevicePortFilterArgs and GetDevicePortFilterOutput values.
// You can construct a concrete instance of `GetDevicePortFilterInput` via:
//
//	GetDevicePortFilterArgs{...}
type GetDevicePortFilterInput interface {
	pulumi.Input

	ToGetDevicePortFilterOutput() GetDevicePortFilterOutput
	ToGetDevicePortFilterOutputWithContext(context.Context) GetDevicePortFilterOutput
}

type GetDevicePortFilterArgs struct {
	Name   pulumi.StringInput      `pulumi:"name"`
	Values pulumi.StringArrayInput `pulumi:"values"`
}

func (GetDevicePortFilterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDevicePortFilter)(nil)).Elem()
}

func (i GetDevicePortFilterArgs) ToGetDevicePortFilterOutput() GetDevicePortFilterOutput {
	return i.ToGetDevicePortFilterOutputWithContext(context.Background())
}

func (i GetDevicePortFilterArgs) ToGetDevicePortFilterOutputWithContext(ctx context.Context) GetDevicePortFilterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetDevicePortFilterOutput)
}

// GetDevicePortFilterArrayInput is an input type that accepts GetDevicePortFilterArray and GetDevicePortFilterArrayOutput values.
// You can construct a concrete instance of `GetDevicePortFilterArrayInput` via:
//
//	GetDevicePortFilterArray{ GetDevicePortFilterArgs{...} }
type GetDevicePortFilterArrayInput interface {
	pulumi.Input

	ToGetDevicePortFilterArrayOutput() GetDevicePortFilterArrayOutput
	ToGetDevicePortFilterArrayOutputWithContext(context.Context) GetDevicePortFilterArrayOutput
}

type GetDevicePortFilterArray []GetDevicePortFilterInput

func (GetDevicePortFilterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetDevicePortFilter)(nil)).Elem()
}

func (i GetDevicePortFilterArray) ToGetDevicePortFilterArrayOutput() GetDevicePortFilterArrayOutput {
	return i.ToGetDevicePortFilterArrayOutputWithContext(context.Background())
}

func (i GetDevicePortFilterArray) ToGetDevicePortFilterArrayOutputWithContext(ctx context.Context) GetDevicePortFilterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetDevicePortFilterArrayOutput)
}

type GetDevicePortFilterOutput struct{ *pulumi.OutputState }

func (GetDevicePortFilterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDevicePortFilter)(nil)).Elem()
}

func (o GetDevicePortFilterOutput) ToGetDevicePortFilterOutput() GetDevicePortFilterOutput {
	return o
}

func (o GetDevicePortFilterOutput) ToGetDevicePortFilterOutputWithContext(ctx context.Context) GetDevicePortFilterOutput {
	return o
}

func (o GetDevicePortFilterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetDevicePortFilter) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetDevicePortFilterOutput) Values() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetDevicePortFilter) []string { return v.Values }).(pulumi.StringArrayOutput)
}

type GetDevicePortFilterArrayOutput struct{ *pulumi.OutputState }

func (GetDevicePortFilterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetDevicePortFilter)(nil)).Elem()
}

func (o GetDevicePortFilterArrayOutput) ToGetDevicePortFilterArrayOutput() GetDevicePortFilterArrayOutput {
	return o
}

func (o GetDevicePortFilterArrayOutput) ToGetDevicePortFilterArrayOutputWithContext(ctx context.Context) GetDevicePortFilterArrayOutput {
	return o
}

func (o GetDevicePortFilterArrayOutput) Index(i pulumi.IntInput) GetDevicePortFilterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetDevicePortFilter {
		return vs[0].([]GetDevicePortFilter)[vs[1].(int)]
	}).(GetDevicePortFilterOutput)
}

type GetHivelocityDevicePortFilter struct {
	Name   string   `pulumi:"name"`
	Values []string `pulumi:"values"`
}

// GetHivelocityDevicePortFilterInput is an input type that accepts GetHivelocityDevicePortFilterArgs and GetHivelocityDevicePortFilterOutput values.
// You can construct a concrete instance of `GetHivelocityDevicePortFilterInput` via:
//
//	GetHivelocityDevicePortFilterArgs{...}
type GetHivelocityDevicePortFilterInput interface {
	pulumi.Input

	ToGetHivelocityDevicePortFilterOutput() GetHivelocityDevicePortFilterOutput
	ToGetHivelocityDevicePortFilterOutputWithContext(context.Context) GetHivelocityDevicePortFilterOutput
}

type GetHivelocityDevicePortFilterArgs struct {
	Name   pulumi.StringInput      `pulumi:"name"`
	Values pulumi.StringArrayInput `pulumi:"values"`
}

func (GetHivelocityDevicePortFilterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetHivelocityDevicePortFilter)(nil)).Elem()
}

func (i GetHivelocityDevicePortFilterArgs) ToGetHivelocityDevicePortFilterOutput() GetHivelocityDevicePortFilterOutput {
	return i.ToGetHivelocityDevicePortFilterOutputWithContext(context.Background())
}

func (i GetHivelocityDevicePortFilterArgs) ToGetHivelocityDevicePortFilterOutputWithContext(ctx context.Context) GetHivelocityDevicePortFilterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetHivelocityDevicePortFilterOutput)
}

// GetHivelocityDevicePortFilterArrayInput is an input type that accepts GetHivelocityDevicePortFilterArray and GetHivelocityDevicePortFilterArrayOutput values.
// You can construct a concrete instance of `GetHivelocityDevicePortFilterArrayInput` via:
//
//	GetHivelocityDevicePortFilterArray{ GetHivelocityDevicePortFilterArgs{...} }
type GetHivelocityDevicePortFilterArrayInput interface {
	pulumi.Input

	ToGetHivelocityDevicePortFilterArrayOutput() GetHivelocityDevicePortFilterArrayOutput
	ToGetHivelocityDevicePortFilterArrayOutputWithContext(context.Context) GetHivelocityDevicePortFilterArrayOutput
}

type GetHivelocityDevicePortFilterArray []GetHivelocityDevicePortFilterInput

func (GetHivelocityDevicePortFilterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetHivelocityDevicePortFilter)(nil)).Elem()
}

func (i GetHivelocityDevicePortFilterArray) ToGetHivelocityDevicePortFilterArrayOutput() GetHivelocityDevicePortFilterArrayOutput {
	return i.ToGetHivelocityDevicePortFilterArrayOutputWithContext(context.Background())
}

func (i GetHivelocityDevicePortFilterArray) ToGetHivelocityDevicePortFilterArrayOutputWithContext(ctx context.Context) GetHivelocityDevicePortFilterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetHivelocityDevicePortFilterArrayOutput)
}

type GetHivelocityDevicePortFilterOutput struct{ *pulumi.OutputState }

func (GetHivelocityDevicePortFilterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetHivelocityDevicePortFilter)(nil)).Elem()
}

func (o GetHivelocityDevicePortFilterOutput) ToGetHivelocityDevicePortFilterOutput() GetHivelocityDevicePortFilterOutput {
	return o
}

func (o GetHivelocityDevicePortFilterOutput) ToGetHivelocityDevicePortFilterOutputWithContext(ctx context.Context) GetHivelocityDevicePortFilterOutput {
	return o
}

func (o GetHivelocityDevicePortFilterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetHivelocityDevicePortFilter) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetHivelocityDevicePortFilterOutput) Values() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetHivelocityDevicePortFilter) []string { return v.Values }).(pulumi.StringArrayOutput)
}

type GetHivelocityDevicePortFilterArrayOutput struct{ *pulumi.OutputState }

func (GetHivelocityDevicePortFilterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetHivelocityDevicePortFilter)(nil)).Elem()
}

func (o GetHivelocityDevicePortFilterArrayOutput) ToGetHivelocityDevicePortFilterArrayOutput() GetHivelocityDevicePortFilterArrayOutput {
	return o
}

func (o GetHivelocityDevicePortFilterArrayOutput) ToGetHivelocityDevicePortFilterArrayOutputWithContext(ctx context.Context) GetHivelocityDevicePortFilterArrayOutput {
	return o
}

func (o GetHivelocityDevicePortFilterArrayOutput) Index(i pulumi.IntInput) GetHivelocityDevicePortFilterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetHivelocityDevicePortFilter {
		return vs[0].([]GetHivelocityDevicePortFilter)[vs[1].(int)]
	}).(GetHivelocityDevicePortFilterOutput)
}

type GetProductFilter struct {
	Name   string   `pulumi:"name"`
	Values []string `pulumi:"values"`
}

// GetProductFilterInput is an input type that accepts GetProductFilterArgs and GetProductFilterOutput values.
// You can construct a concrete instance of `GetProductFilterInput` via:
//
//	GetProductFilterArgs{...}
type GetProductFilterInput interface {
	pulumi.Input

	ToGetProductFilterOutput() GetProductFilterOutput
	ToGetProductFilterOutputWithContext(context.Context) GetProductFilterOutput
}

type GetProductFilterArgs struct {
	Name   pulumi.StringInput      `pulumi:"name"`
	Values pulumi.StringArrayInput `pulumi:"values"`
}

func (GetProductFilterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProductFilter)(nil)).Elem()
}

func (i GetProductFilterArgs) ToGetProductFilterOutput() GetProductFilterOutput {
	return i.ToGetProductFilterOutputWithContext(context.Background())
}

func (i GetProductFilterArgs) ToGetProductFilterOutputWithContext(ctx context.Context) GetProductFilterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetProductFilterOutput)
}

// GetProductFilterArrayInput is an input type that accepts GetProductFilterArray and GetProductFilterArrayOutput values.
// You can construct a concrete instance of `GetProductFilterArrayInput` via:
//
//	GetProductFilterArray{ GetProductFilterArgs{...} }
type GetProductFilterArrayInput interface {
	pulumi.Input

	ToGetProductFilterArrayOutput() GetProductFilterArrayOutput
	ToGetProductFilterArrayOutputWithContext(context.Context) GetProductFilterArrayOutput
}

type GetProductFilterArray []GetProductFilterInput

func (GetProductFilterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetProductFilter)(nil)).Elem()
}

func (i GetProductFilterArray) ToGetProductFilterArrayOutput() GetProductFilterArrayOutput {
	return i.ToGetProductFilterArrayOutputWithContext(context.Background())
}

func (i GetProductFilterArray) ToGetProductFilterArrayOutputWithContext(ctx context.Context) GetProductFilterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetProductFilterArrayOutput)
}

type GetProductFilterOutput struct{ *pulumi.OutputState }

func (GetProductFilterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProductFilter)(nil)).Elem()
}

func (o GetProductFilterOutput) ToGetProductFilterOutput() GetProductFilterOutput {
	return o
}

func (o GetProductFilterOutput) ToGetProductFilterOutputWithContext(ctx context.Context) GetProductFilterOutput {
	return o
}

func (o GetProductFilterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductFilter) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetProductFilterOutput) Values() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetProductFilter) []string { return v.Values }).(pulumi.StringArrayOutput)
}

type GetProductFilterArrayOutput struct{ *pulumi.OutputState }

func (GetProductFilterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetProductFilter)(nil)).Elem()
}

func (o GetProductFilterArrayOutput) ToGetProductFilterArrayOutput() GetProductFilterArrayOutput {
	return o
}

func (o GetProductFilterArrayOutput) ToGetProductFilterArrayOutputWithContext(ctx context.Context) GetProductFilterArrayOutput {
	return o
}

func (o GetProductFilterArrayOutput) Index(i pulumi.IntInput) GetProductFilterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetProductFilter {
		return vs[0].([]GetProductFilter)[vs[1].(int)]
	}).(GetProductFilterOutput)
}

type GetSshKeyFilter struct {
	Name   string   `pulumi:"name"`
	Values []string `pulumi:"values"`
}

// GetSshKeyFilterInput is an input type that accepts GetSshKeyFilterArgs and GetSshKeyFilterOutput values.
// You can construct a concrete instance of `GetSshKeyFilterInput` via:
//
//	GetSshKeyFilterArgs{...}
type GetSshKeyFilterInput interface {
	pulumi.Input

	ToGetSshKeyFilterOutput() GetSshKeyFilterOutput
	ToGetSshKeyFilterOutputWithContext(context.Context) GetSshKeyFilterOutput
}

type GetSshKeyFilterArgs struct {
	Name   pulumi.StringInput      `pulumi:"name"`
	Values pulumi.StringArrayInput `pulumi:"values"`
}

func (GetSshKeyFilterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSshKeyFilter)(nil)).Elem()
}

func (i GetSshKeyFilterArgs) ToGetSshKeyFilterOutput() GetSshKeyFilterOutput {
	return i.ToGetSshKeyFilterOutputWithContext(context.Background())
}

func (i GetSshKeyFilterArgs) ToGetSshKeyFilterOutputWithContext(ctx context.Context) GetSshKeyFilterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSshKeyFilterOutput)
}

// GetSshKeyFilterArrayInput is an input type that accepts GetSshKeyFilterArray and GetSshKeyFilterArrayOutput values.
// You can construct a concrete instance of `GetSshKeyFilterArrayInput` via:
//
//	GetSshKeyFilterArray{ GetSshKeyFilterArgs{...} }
type GetSshKeyFilterArrayInput interface {
	pulumi.Input

	ToGetSshKeyFilterArrayOutput() GetSshKeyFilterArrayOutput
	ToGetSshKeyFilterArrayOutputWithContext(context.Context) GetSshKeyFilterArrayOutput
}

type GetSshKeyFilterArray []GetSshKeyFilterInput

func (GetSshKeyFilterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetSshKeyFilter)(nil)).Elem()
}

func (i GetSshKeyFilterArray) ToGetSshKeyFilterArrayOutput() GetSshKeyFilterArrayOutput {
	return i.ToGetSshKeyFilterArrayOutputWithContext(context.Background())
}

func (i GetSshKeyFilterArray) ToGetSshKeyFilterArrayOutputWithContext(ctx context.Context) GetSshKeyFilterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSshKeyFilterArrayOutput)
}

type GetSshKeyFilterOutput struct{ *pulumi.OutputState }

func (GetSshKeyFilterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSshKeyFilter)(nil)).Elem()
}

func (o GetSshKeyFilterOutput) ToGetSshKeyFilterOutput() GetSshKeyFilterOutput {
	return o
}

func (o GetSshKeyFilterOutput) ToGetSshKeyFilterOutputWithContext(ctx context.Context) GetSshKeyFilterOutput {
	return o
}

func (o GetSshKeyFilterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetSshKeyFilter) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetSshKeyFilterOutput) Values() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSshKeyFilter) []string { return v.Values }).(pulumi.StringArrayOutput)
}

type GetSshKeyFilterArrayOutput struct{ *pulumi.OutputState }

func (GetSshKeyFilterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetSshKeyFilter)(nil)).Elem()
}

func (o GetSshKeyFilterArrayOutput) ToGetSshKeyFilterArrayOutput() GetSshKeyFilterArrayOutput {
	return o
}

func (o GetSshKeyFilterArrayOutput) ToGetSshKeyFilterArrayOutputWithContext(ctx context.Context) GetSshKeyFilterArrayOutput {
	return o
}

func (o GetSshKeyFilterArrayOutput) Index(i pulumi.IntInput) GetSshKeyFilterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetSshKeyFilter {
		return vs[0].([]GetSshKeyFilter)[vs[1].(int)]
	}).(GetSshKeyFilterOutput)
}

type OrderGroupBareMetalDevice struct {
	// When set, prefer only bonded devices
	Bonded *bool `pulumi:"bonded"`
	// Device ID
	DeviceId *int `pulumi:"deviceId"`
	// Force deployment of this Device ID (internal use only)
	ForceDeviceId *int `pulumi:"forceDeviceId"`
	// Hostname for this device
	Hostname string `pulumi:"hostname"`
	// IgnitionConfig ID
	IgnitionId *int `pulumi:"ignitionId"`
	// Last time this device was updated
	LastUpdated *string `pulumi:"lastUpdated"`
	// Deploy device in this location
	LocationName string `pulumi:"locationName"`
	// Order ID
	OrderId *int `pulumi:"orderId"`
	// Operating system to install on device
	OsName string `pulumi:"osName"`
	// Billing period for device
	Period *string `pulumi:"period"`
	// Power status
	PowerStatus *string `pulumi:"powerStatus"`
	// Primary IP of device
	PrimaryIp *string `pulumi:"primaryIp"`
	// Product ID to pick from the stock
	ProductId int `pulumi:"productId"`
	// Product Name
	ProductName *string `pulumi:"productName"`
	// ID of a SSH Key to apply for device
	PublicSshKeyId *int `pulumi:"publicSshKeyId"`
	// Post-install script for device
	Script *string `pulumi:"script"`
	// Service ID
	ServiceId *int `pulumi:"serviceId"`
	// Tags to apply for device
	Tags []string `pulumi:"tags"`
	// VLAN ID
	//
	// Deprecated: This field is deprecated. Please use a VlanDetail resource instead.
	VlanId *int `pulumi:"vlanId"`
}

// OrderGroupBareMetalDeviceInput is an input type that accepts OrderGroupBareMetalDeviceArgs and OrderGroupBareMetalDeviceOutput values.
// You can construct a concrete instance of `OrderGroupBareMetalDeviceInput` via:
//
//	OrderGroupBareMetalDeviceArgs{...}
type OrderGroupBareMetalDeviceInput interface {
	pulumi.Input

	ToOrderGroupBareMetalDeviceOutput() OrderGroupBareMetalDeviceOutput
	ToOrderGroupBareMetalDeviceOutputWithContext(context.Context) OrderGroupBareMetalDeviceOutput
}

type OrderGroupBareMetalDeviceArgs struct {
	// When set, prefer only bonded devices
	Bonded pulumi.BoolPtrInput `pulumi:"bonded"`
	// Device ID
	DeviceId pulumi.IntPtrInput `pulumi:"deviceId"`
	// Force deployment of this Device ID (internal use only)
	ForceDeviceId pulumi.IntPtrInput `pulumi:"forceDeviceId"`
	// Hostname for this device
	Hostname pulumi.StringInput `pulumi:"hostname"`
	// IgnitionConfig ID
	IgnitionId pulumi.IntPtrInput `pulumi:"ignitionId"`
	// Last time this device was updated
	LastUpdated pulumi.StringPtrInput `pulumi:"lastUpdated"`
	// Deploy device in this location
	LocationName pulumi.StringInput `pulumi:"locationName"`
	// Order ID
	OrderId pulumi.IntPtrInput `pulumi:"orderId"`
	// Operating system to install on device
	OsName pulumi.StringInput `pulumi:"osName"`
	// Billing period for device
	Period pulumi.StringPtrInput `pulumi:"period"`
	// Power status
	PowerStatus pulumi.StringPtrInput `pulumi:"powerStatus"`
	// Primary IP of device
	PrimaryIp pulumi.StringPtrInput `pulumi:"primaryIp"`
	// Product ID to pick from the stock
	ProductId pulumi.IntInput `pulumi:"productId"`
	// Product Name
	ProductName pulumi.StringPtrInput `pulumi:"productName"`
	// ID of a SSH Key to apply for device
	PublicSshKeyId pulumi.IntPtrInput `pulumi:"publicSshKeyId"`
	// Post-install script for device
	Script pulumi.StringPtrInput `pulumi:"script"`
	// Service ID
	ServiceId pulumi.IntPtrInput `pulumi:"serviceId"`
	// Tags to apply for device
	Tags pulumi.StringArrayInput `pulumi:"tags"`
	// VLAN ID
	//
	// Deprecated: This field is deprecated. Please use a VlanDetail resource instead.
	VlanId pulumi.IntPtrInput `pulumi:"vlanId"`
}

func (OrderGroupBareMetalDeviceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*OrderGroupBareMetalDevice)(nil)).Elem()
}

func (i OrderGroupBareMetalDeviceArgs) ToOrderGroupBareMetalDeviceOutput() OrderGroupBareMetalDeviceOutput {
	return i.ToOrderGroupBareMetalDeviceOutputWithContext(context.Background())
}

func (i OrderGroupBareMetalDeviceArgs) ToOrderGroupBareMetalDeviceOutputWithContext(ctx context.Context) OrderGroupBareMetalDeviceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrderGroupBareMetalDeviceOutput)
}

// OrderGroupBareMetalDeviceArrayInput is an input type that accepts OrderGroupBareMetalDeviceArray and OrderGroupBareMetalDeviceArrayOutput values.
// You can construct a concrete instance of `OrderGroupBareMetalDeviceArrayInput` via:
//
//	OrderGroupBareMetalDeviceArray{ OrderGroupBareMetalDeviceArgs{...} }
type OrderGroupBareMetalDeviceArrayInput interface {
	pulumi.Input

	ToOrderGroupBareMetalDeviceArrayOutput() OrderGroupBareMetalDeviceArrayOutput
	ToOrderGroupBareMetalDeviceArrayOutputWithContext(context.Context) OrderGroupBareMetalDeviceArrayOutput
}

type OrderGroupBareMetalDeviceArray []OrderGroupBareMetalDeviceInput

func (OrderGroupBareMetalDeviceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]OrderGroupBareMetalDevice)(nil)).Elem()
}

func (i OrderGroupBareMetalDeviceArray) ToOrderGroupBareMetalDeviceArrayOutput() OrderGroupBareMetalDeviceArrayOutput {
	return i.ToOrderGroupBareMetalDeviceArrayOutputWithContext(context.Background())
}

func (i OrderGroupBareMetalDeviceArray) ToOrderGroupBareMetalDeviceArrayOutputWithContext(ctx context.Context) OrderGroupBareMetalDeviceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrderGroupBareMetalDeviceArrayOutput)
}

type OrderGroupBareMetalDeviceOutput struct{ *pulumi.OutputState }

func (OrderGroupBareMetalDeviceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*OrderGroupBareMetalDevice)(nil)).Elem()
}

func (o OrderGroupBareMetalDeviceOutput) ToOrderGroupBareMetalDeviceOutput() OrderGroupBareMetalDeviceOutput {
	return o
}

func (o OrderGroupBareMetalDeviceOutput) ToOrderGroupBareMetalDeviceOutputWithContext(ctx context.Context) OrderGroupBareMetalDeviceOutput {
	return o
}

// When set, prefer only bonded devices
func (o OrderGroupBareMetalDeviceOutput) Bonded() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) *bool { return v.Bonded }).(pulumi.BoolPtrOutput)
}

// Device ID
func (o OrderGroupBareMetalDeviceOutput) DeviceId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) *int { return v.DeviceId }).(pulumi.IntPtrOutput)
}

// Force deployment of this Device ID (internal use only)
func (o OrderGroupBareMetalDeviceOutput) ForceDeviceId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) *int { return v.ForceDeviceId }).(pulumi.IntPtrOutput)
}

// Hostname for this device
func (o OrderGroupBareMetalDeviceOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) string { return v.Hostname }).(pulumi.StringOutput)
}

// IgnitionConfig ID
func (o OrderGroupBareMetalDeviceOutput) IgnitionId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) *int { return v.IgnitionId }).(pulumi.IntPtrOutput)
}

// Last time this device was updated
func (o OrderGroupBareMetalDeviceOutput) LastUpdated() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) *string { return v.LastUpdated }).(pulumi.StringPtrOutput)
}

// Deploy device in this location
func (o OrderGroupBareMetalDeviceOutput) LocationName() pulumi.StringOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) string { return v.LocationName }).(pulumi.StringOutput)
}

// Order ID
func (o OrderGroupBareMetalDeviceOutput) OrderId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) *int { return v.OrderId }).(pulumi.IntPtrOutput)
}

// Operating system to install on device
func (o OrderGroupBareMetalDeviceOutput) OsName() pulumi.StringOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) string { return v.OsName }).(pulumi.StringOutput)
}

// Billing period for device
func (o OrderGroupBareMetalDeviceOutput) Period() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) *string { return v.Period }).(pulumi.StringPtrOutput)
}

// Power status
func (o OrderGroupBareMetalDeviceOutput) PowerStatus() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) *string { return v.PowerStatus }).(pulumi.StringPtrOutput)
}

// Primary IP of device
func (o OrderGroupBareMetalDeviceOutput) PrimaryIp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) *string { return v.PrimaryIp }).(pulumi.StringPtrOutput)
}

// Product ID to pick from the stock
func (o OrderGroupBareMetalDeviceOutput) ProductId() pulumi.IntOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) int { return v.ProductId }).(pulumi.IntOutput)
}

// Product Name
func (o OrderGroupBareMetalDeviceOutput) ProductName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) *string { return v.ProductName }).(pulumi.StringPtrOutput)
}

// ID of a SSH Key to apply for device
func (o OrderGroupBareMetalDeviceOutput) PublicSshKeyId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) *int { return v.PublicSshKeyId }).(pulumi.IntPtrOutput)
}

// Post-install script for device
func (o OrderGroupBareMetalDeviceOutput) Script() pulumi.StringPtrOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) *string { return v.Script }).(pulumi.StringPtrOutput)
}

// Service ID
func (o OrderGroupBareMetalDeviceOutput) ServiceId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) *int { return v.ServiceId }).(pulumi.IntPtrOutput)
}

// Tags to apply for device
func (o OrderGroupBareMetalDeviceOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

// VLAN ID
//
// Deprecated: This field is deprecated. Please use a VlanDetail resource instead.
func (o OrderGroupBareMetalDeviceOutput) VlanId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v OrderGroupBareMetalDevice) *int { return v.VlanId }).(pulumi.IntPtrOutput)
}

type OrderGroupBareMetalDeviceArrayOutput struct{ *pulumi.OutputState }

func (OrderGroupBareMetalDeviceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]OrderGroupBareMetalDevice)(nil)).Elem()
}

func (o OrderGroupBareMetalDeviceArrayOutput) ToOrderGroupBareMetalDeviceArrayOutput() OrderGroupBareMetalDeviceArrayOutput {
	return o
}

func (o OrderGroupBareMetalDeviceArrayOutput) ToOrderGroupBareMetalDeviceArrayOutputWithContext(ctx context.Context) OrderGroupBareMetalDeviceArrayOutput {
	return o
}

func (o OrderGroupBareMetalDeviceArrayOutput) Index(i pulumi.IntInput) OrderGroupBareMetalDeviceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) OrderGroupBareMetalDevice {
		return vs[0].([]OrderGroupBareMetalDevice)[vs[1].(int)]
	}).(OrderGroupBareMetalDeviceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OrderGroupDetailBareMetalDeviceInput)(nil)).Elem(), OrderGroupDetailBareMetalDeviceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*OrderGroupDetailBareMetalDeviceArrayInput)(nil)).Elem(), OrderGroupDetailBareMetalDeviceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetBareMetalDeviceFilterInput)(nil)).Elem(), GetBareMetalDeviceFilterArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetBareMetalDeviceFilterArrayInput)(nil)).Elem(), GetBareMetalDeviceFilterArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetDeviceFilterInput)(nil)).Elem(), GetDeviceFilterArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetDeviceFilterArrayInput)(nil)).Elem(), GetDeviceFilterArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetDevicePortFilterInput)(nil)).Elem(), GetDevicePortFilterArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetDevicePortFilterArrayInput)(nil)).Elem(), GetDevicePortFilterArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetHivelocityDevicePortFilterInput)(nil)).Elem(), GetHivelocityDevicePortFilterArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetHivelocityDevicePortFilterArrayInput)(nil)).Elem(), GetHivelocityDevicePortFilterArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetProductFilterInput)(nil)).Elem(), GetProductFilterArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetProductFilterArrayInput)(nil)).Elem(), GetProductFilterArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetSshKeyFilterInput)(nil)).Elem(), GetSshKeyFilterArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetSshKeyFilterArrayInput)(nil)).Elem(), GetSshKeyFilterArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*OrderGroupBareMetalDeviceInput)(nil)).Elem(), OrderGroupBareMetalDeviceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*OrderGroupBareMetalDeviceArrayInput)(nil)).Elem(), OrderGroupBareMetalDeviceArray{})
	pulumi.RegisterOutputType(OrderGroupDetailBareMetalDeviceOutput{})
	pulumi.RegisterOutputType(OrderGroupDetailBareMetalDeviceArrayOutput{})
	pulumi.RegisterOutputType(GetBareMetalDeviceFilterOutput{})
	pulumi.RegisterOutputType(GetBareMetalDeviceFilterArrayOutput{})
	pulumi.RegisterOutputType(GetDeviceFilterOutput{})
	pulumi.RegisterOutputType(GetDeviceFilterArrayOutput{})
	pulumi.RegisterOutputType(GetDevicePortFilterOutput{})
	pulumi.RegisterOutputType(GetDevicePortFilterArrayOutput{})
	pulumi.RegisterOutputType(GetHivelocityDevicePortFilterOutput{})
	pulumi.RegisterOutputType(GetHivelocityDevicePortFilterArrayOutput{})
	pulumi.RegisterOutputType(GetProductFilterOutput{})
	pulumi.RegisterOutputType(GetProductFilterArrayOutput{})
	pulumi.RegisterOutputType(GetSshKeyFilterOutput{})
	pulumi.RegisterOutputType(GetSshKeyFilterArrayOutput{})
	pulumi.RegisterOutputType(OrderGroupBareMetalDeviceOutput{})
	pulumi.RegisterOutputType(OrderGroupBareMetalDeviceArrayOutput{})
}
