// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IgnitionDetail extends pulumi.CustomResource {
    /**
     * Get an existing IgnitionDetail resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IgnitionDetailState, opts?: pulumi.CustomResourceOptions): IgnitionDetail {
        return new IgnitionDetail(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'hivelocity:index/ignitionDetail:IgnitionDetail';

    /**
     * Returns true if the given object is an instance of IgnitionDetail.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IgnitionDetail {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IgnitionDetail.__pulumiType;
    }

    /**
     * String of the JSON contents of the ignition file
     */
    public readonly contents!: pulumi.Output<string>;
    /**
     * Name of ignition file resource
     */
    public readonly name!: pulumi.Output<string>;

    /**
     * Create a IgnitionDetail resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IgnitionDetailArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IgnitionDetailArgs | IgnitionDetailState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IgnitionDetailState | undefined;
            resourceInputs["contents"] = state ? state.contents : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as IgnitionDetailArgs | undefined;
            if ((!args || args.contents === undefined) && !opts.urn) {
                throw new Error("Missing required property 'contents'");
            }
            resourceInputs["contents"] = args ? args.contents : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const aliasOpts = { aliases: [{ type: "hivelocity:index/ignition:ignition" }] };
        opts = pulumi.mergeOptions(opts, aliasOpts);
        super(IgnitionDetail.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IgnitionDetail resources.
 */
export interface IgnitionDetailState {
    /**
     * String of the JSON contents of the ignition file
     */
    contents?: pulumi.Input<string>;
    /**
     * Name of ignition file resource
     */
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IgnitionDetail resource.
 */
export interface IgnitionDetailArgs {
    /**
     * String of the JSON contents of the ignition file
     */
    contents: pulumi.Input<string>;
    /**
     * Name of ignition file resource
     */
    name?: pulumi.Input<string>;
}
